FROM node:22.21.1-alpine AS runtime
WORKDIR /app

ARG SKANHAND_OPENAI_API_KEY
ARG SKANHAND_OPENAI_URL
ARG SKANHAND_BLOG_URL
ENV SKANHAND_OPENAI_API_KEY=$SKANHAND_OPENAI_API_KEY
ENV SKANHAND_OPENAI_URL=$SKANHAND_OPENAI_URL
ENV SKANHAND_BLOG_URL=$SKANHAND_BLOG_URL

COPY . .

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD ["node", "./dist/server/entry.mjs"]